#coding: utf-8

'''
File: generate_necessary_routes.py
Author: John Holbrook
Site: http://johnholbrook.us
Github: dhmmjoph
Description: generates a .tsv file containing every possible
	combination of items in a list, which represents every possible
	(direction-independent) route between two BCN metro stations.
	The time and distances of each route will later be computed by
	another script.
Date: 22 April 2017
'''

stations = ["aeroport t1 metro, barcelona",
"aeroport T2 metro, barcelona",
"alfons x metro, barcelona",
"almeda metro, barcelona",
"arc de triomf metro, barcelona",
"artigues metro, barcelona",
"avinguda carrilet metro, barcelona",
"avinguda tibidabo metro, barcelona",
"bac de roda metro, barcelona",
"badal metro, barcelona",
"badalona pompeu fabra metro, barcelona",
"barceloneta metro, barcelona",
"baro de vivir metro, barcelona",
"bellvitge metro, barcelona",
"besos metro, barcelona",
"besos mar metro, barcelona",
"bogatell metro, barcelona",
"bon pastor metro, barcelona",
"camp de l'arpa metro, barcelona",
"can boixeres metro, barcelona",
"can cuias metro, barcelona",
"can peixauet metro, barcelona",
"can serra metro, barcelona",
"can tries metro, barcelona",
"can vidalet metro, barcelona",
"can zam metro, barcelona",
"canyelles metro, barcelona",
"casa de l'aigua metro, barcelona",
'catalunya metro, barcelona',
'centric metro, barcelona',
'via olimpica metro, barcelona',
'ciutat meridiana metro, barcelona',
'clot metro, barcelona',
'collblanc metro, barcelona',
'congres metro, barcelona',
'cornella centre metro, barcelona',
'cornella riera metro, barcelona',
'Diagonal, Barcelona, Spain',
'Drassanes metro, barcelona',
'el carmel metro, barcelona',
'el coll metro, barcelona',
'el maresme metro, barcelona',
'el prat estacio metro, barcelona',
'el putxet metro, barcelona',
'encants metro, barcelona',
'entenca metro, barcelona',
'ernest lluch metro, barcelona',
'esglesia major metro, barcelona',
'espanya metro, barcelona',
'europa metro, barcelona',
'Fabra metro, barcelona',
'Fira metro, barcelona',
'Florida metro, barcelona',
'Fondo metro, barcelona',
'Fontana metro, barcelona',
'Gavarra metro, barcelona',
'girona metro, barcelona',
'glories metro, barcelona',
'gorg metro, barcelona',
'gornal metro, barcelona',
'gracia metro, barcelona',
'guinardo metro, barcelona',
'horta metro, barcelona',
'hospital de bellvitge metro, barcelona',
'dos de maig metro, barcelona',
'hospital clinic metro, barcelona',
'hostafrancs metro, barcelona',
'ildefons cerda metro, barcelona',
'Jaume I metro, barcelona',
'Joanic metro, barcelona',
'Bonanova metro, barcelona',
'La pau metro, barcelona',
'Sagrera metro, barcelona',
'La salut metro, barcelona',
'Les Corts metro, barcelona',
'Les moreres metro, barcelona',
'Les tres torres metro, barcelona',
'Lesseps metro, barcelona',
'Liceu metro, barcelona',
'Llacuna metro, barcelona',
'llefia metro, barcelona',
'llucmajor metro, barcelona',
'Magoria metro, barcelona',
'Maragall metro, barcelona',
'Maria Cristina metro, barcelona',
'Marina metro, barcelona',
'Mas blau metro, barcelona',
'Mercabarna metro, barcelona',
'Mercat Nou metro, barcelona',
'Moli Nou metro, barcelona',
'Montbau metro, barcelona',
'Monumental metro, barcelona',
'Mundet metro, barcelona',
'Muntaner metro, barcelona',
'Navas metro, barcelona',
'Onza de Setembre metro, barcelona',
'Palau Reial metro, barcelona',
'Padua metro, barcelona',
'Parallel metro, barcelona',
'Parc logistic metro, barcelona',
'Parc nou metro, barcelona',
'passeig de gracia metro, barcelona',
'penitents metro, barcelona',
'pep ventura metro, barcelona',
'placa molina metro, barcelona',
'placa de sants metro, barcelona',
'placa del centre metro, barcelona',
'poblenou metro, barcelona',
'poble sec metro, barcelona',
'provenca metro, barcelona',
'pubilla cases metro, barcelona',
'rambla just oliveres metro, barcelona',
'reina elisenda metro, barcelona',
'rocafort metro, barcelona',
'roquetes metro, barcelona',
'sagrada familia metro, barcelona',
'sant andreu metro, barcelona',
'sant antoni metro, barcelona',
'sant boi metro, barcelona',
'sant gervasi metro, barcelona',
'sant ildefons metro, 08940 Cornellà de Llobregat, barcelona',
'sant josep metro, barcelona',
'sant marti metro, barcelona',
'sant roc metro, barcelona',
'santa coloma metro, barcelona',
'santa eulalia metro, barcelona',
'santa rosa metro, barcelona',
'sants estacio metro, barcelona',
'sarria metro, barcelona',
'selva de mar metro, barcelona',
'singuerlin metro, barcelona',
'tarragona metro, barcelona',
'tetuan metro, barcelona',
'torras i bages metro, barcelona',
'torrassa metro, barcelona',
'torre baro metro, barcelona',
'trinitat nova metro, barcelona',
'trinitat vella metro, barcelona',
'universitat metro, barcelona',
'urgell metro, barcelona',
'urquinaona metro, barcelona',
'valldaura metro, barcelona',
'vall d\'hebron metro, barcelona',
'verdaguer metro, barcelona',
'verneda metro, barcelona',
'via julia metro, barcelona',
'vilapicina metro, barcelona',
'virrei amat metro, barcelona',
'zona universitaria metro, barcelona',]

with open("list_of_routes.tsv", 'w') as f:
	for i in range(len(stations)):
		for dest in stations[i+1:]:
			f.write("%s\t%s\n" % (stations[i], dest))